name: bit_ascol
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.1.0
  image_picker: ^1.1.2
  uuid: ^4.4.2
  flutter_pdfview: ^1.3.2
  file_picker: ^8.0.7
  syncfusion_flutter_pdfviewer: ^26.2.8
  firebase_core: ^3.4.0
  http: ^1.2.2
  fluttertoast: ^8.2.6
  url_launcher: ^6.3.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  page_transition: ^2.1.0
  firebase_database: ^11.0.4
  path: ^1.9.0
  photo_view: ^0.15.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.0
  connectivity_plus: ^6.0.5
  retry: ^3.1.2
  loading_indicator: ^3.1.1
  email_validator: ^3.0.0
  flutter_gemini: ^2.0.5
  provider: ^6.1.2
  get_it: ^7.7.0
  emoji_picker_flutter: ^2.2.0
  loading_animation_widget: ^1.2.1
  material_design_icons_flutter: ^7.0.7296
  open_file: ^3.5.3
  flutter_local_notifications: ^18.0.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^4.2.1
  intl: ^0.19.0
  firebase_analytics: ^11.3.0
  multi_image_picker_plus: ^0.0.5
  carousel_slider: ^5.0.0
  eva_icons_flutter: ^3.1.0
  dio: ^5.7.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/


  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
          weight: 300

    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/robotoblack.ttf
          weight: 400
