// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvt3ssQJsgJoRUcAEmZt2oFuDMquOyhZs',
    appId: '1:662072148304:web:1ecce419eb71150c066c55',
    messagingSenderId: '662072148304',
    projectId: 'bitascol-a24f2',
    authDomain: 'bitascol-a24f2.firebaseapp.com',
    storageBucket: 'bitascol-a24f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbrBm7OmrpQQukOnvfMuDB9g61lgxDyIU',
    appId: '1:662072148304:android:2633b644fb6e0e65066c55',
    messagingSenderId: '662072148304',
    projectId: 'bitascol-a24f2',
    storageBucket: 'bitascol-a24f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJIFtDzkiLafv-C-MCe4J6I9jLzHwSVjY',
    appId: '1:662072148304:ios:4e8112dcfe17123a066c55',
    messagingSenderId: '662072148304',
    projectId: 'bitascol-a24f2',
    storageBucket: 'bitascol-a24f2.appspot.com',
    iosBundleId: 'com.example.bitAscol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJIFtDzkiLafv-C-MCe4J6I9jLzHwSVjY',
    appId: '1:662072148304:ios:4e8112dcfe17123a066c55',
    messagingSenderId: '662072148304',
    projectId: 'bitascol-a24f2',
    storageBucket: 'bitascol-a24f2.appspot.com',
    iosBundleId: 'com.example.bitAscol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvt3ssQJsgJoRUcAEmZt2oFuDMquOyhZs',
    appId: '1:662072148304:web:d55a75a0d9de2ffc066c55',
    messagingSenderId: '662072148304',
    projectId: 'bitascol-a24f2',
    authDomain: 'bitascol-a24f2.firebaseapp.com',
    storageBucket: 'bitascol-a24f2.appspot.com',
  );
}
